services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_DATABASE: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root

  app:
    container_name: app
    build: .docker/php-fpm
    restart: unless-stopped
    volumes:
      - .:/var/www
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: root
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mariadb
